app = "aulagpt-backend"  # Nombre de tu aplicación backend

[build]
  builder = "heroku/buildpacks:python"  # Usar el buildpack de Python

[[mounts]]
  destination = "/data"
  source = "mysql_data"  # Volumen creado para MySQL

[env]
  MYSQL_ROOT_PASSWORD = "1234"  # Cambia por una clave secreta
  MYSQL_USER = "root"           # Usuario MySQL
  MYSQL_PASSWORD = "1234"       # Contraseña del usuario
  MYSQL_DATABASE = "aulagpt_db" # Nombre de la base de datos
  DATABASE_URL = "mysql://root:1234@localhost:3306/aulagpt_db"  # URL de conexión MySQL
