# fly.toml app configuration file generated for aulagpt-backend on 2025-03-28T20:59:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aulagpt-backend'
primary_region = 'mad'

[build]
  dockerfile = 'Dockerfile'

[env]
  ALLOWED_HOSTS = 'aulagpt-backend.fly.dev'
  DEBUG = 'false'
  DJANGO_SECRET_KEY = 'tu_clave_secreta'

[[services]]
  protocol = 'tcp'
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ['http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
