app = "aulagpt-mysql"
primary_region = "mad"

[build]

[env]
  MYSQL_DATABASE = "aulagpt_db"
  MYSQL_USER = "aulagpt_user"
  MYSQL_PASSWORD = "1234"
  MYSQL_ROOT_PASSWORD = "1234"

[mounts]
  source = "mysql_data"
  destination = "/var/lib/mysql"

[services]
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 3306

  [[services.ports]]
    port = 3306
    handlers = ["pg_tls"]

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "30s"
    timeout = "5s"
    restart_limit = 6
